In [2]:
import numpy as np

The Basics 

In [15]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[3.1,2.2,1.3],[4.4,5.5,6.6]])
print(b)

[[3.1 2.2 1.3]
 [4.4 5.5 6.6]]


In [6]:
#Get dimention
print (a.ndim)

1


In [7]:
#Get dimention
print (b.ndim)

2


In [8]:
#Get shape
b.shape

(2, 3)

In [ ]:
#Get shape
a.dtype

In [20]:
#Get size by Byte
a.itemsize
b.itemsize

8

In [19]:
#Get total size
a.nbytes

12